# Generated by Django 5.0.1 on 2024-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('book', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='DangoBook',
        ),
    ]
