# Generated by Django 5.0.1 on 2024-01-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangobook',
            name='body',
            field=models.CharField(max_length=100000),
        ),
    ]
