# Generated by Django 5.0.1 on 2024-01-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_pdfbook_description_alter_pdfbook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfbook',
            name='book',
            field=models.FileField(upload_to='media/pdf/'),
        ),
    ]
