# Generated by Django 5.0.1 on 2024-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0005_alter_pdfbook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfbook',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
