# Generated by Django 5.0.1 on 2024-01-26 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0008_comment_date_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_c',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 17, 57, 31, 780015)),
        ),
    ]
